/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"
#include <errno.h>
#include <stdio.h>
#include <stdbool.h>
#include <math.h>
#include <stdlib.h>

int menu(){
	int opcion;
	do{
		printf("\n\nBienvenido a la calculadora porfavor introduzca que operación desea realizar:"
		   		"\n 1.Introduzca 1 para realizar una suma."
				"\n 2.Introduzca 2 para realizar una resta."
				"\n 3.Introduzca 3 para realizar una multiplicación."
				"\n 4.Introduzca 4 para realizar una división."
				"\n 5.Salir\n");
		scanf("%d",&opcion);
	}while(opcion>5 || opcion<1);
	
	return opcion;
}

void
calprog_1(char *host, double arg1, double arg2,int opcion)
{
	CLIENT *clnt;
	calc_res  *result;
	bool valor=true;

#ifndef	DEBUG
	clnt = clnt_create (host, CALPROG, CAL_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	switch (opcion){
	case 1:
		result = add_1(arg1, arg2, clnt);
		if (result == (calc_res *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		printf("\nEl resultado es %0lf \n",result->calc_res_u.result);
		break;
	case 2:
		result = substract_1(arg1, arg2, clnt);
		if (result == (calc_res *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		printf("\nEl resultado es %lf \n",result->calc_res_u.result);
		break;
	case 3:
		result = multiply_1(arg1, arg2, clnt);
		if (result == (calc_res *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		printf("\nEl resultado es %lf \n",result->calc_res_u.result);
		break;
	case 4:
		result = divide_1(arg1, arg2, clnt);
		if (result == (calc_res *) NULL) {
			clnt_perror (clnt, "call failed");
		}else if(result->errnum==-1){
			printf("\nNo se puede divdir por 0\n");
		}else{
			printf("\nEl resultado es %lf \n",result->calc_res_u.result);
		}
		break;
	case 5:
		exit(0);
	default:
		break;
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	double num1=0, num2=0;
	int opcion;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	host = argv[1];
	do{
		opcion = menu();
		if(opcion!=5){
			printf("Introduzca el primer valor: ");
			scanf("%lf",&num1);
			printf("Introduzca el segundo valor: ");
			scanf("%lf",&num2);
			calprog_1 (host,num1,num2,opcion);
		}
	}while(opcion!=5);
exit (0);
}
