/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "calc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

calc_res *
add_1(double_vector arg1,  CLIENT *clnt)
{
	static calc_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, ADD,
		(xdrproc_t) xdr_double_vector, (caddr_t) &arg1,
		(xdrproc_t) xdr_calc_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

calc_res *
substract_1(double_vector arg1,  CLIENT *clnt)
{
	static calc_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SUBSTRACT,
		(xdrproc_t) xdr_double_vector, (caddr_t) &arg1,
		(xdrproc_t) xdr_calc_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

calc_res *
multiply_1(double_vector arg1,  CLIENT *clnt)
{
	static calc_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, MULTIPLY,
		(xdrproc_t) xdr_double_vector, (caddr_t) &arg1,
		(xdrproc_t) xdr_calc_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

calc_res *
divide_1(double_vector arg1,  CLIENT *clnt)
{
	static calc_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, DIVIDE,
		(xdrproc_t) xdr_double_vector, (caddr_t) &arg1,
		(xdrproc_t) xdr_calc_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
