/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"
#include <errno.h>
#include <stdio.h>
#include <stdbool.h>
#include <math.h>
#include <stdlib.h>

#define MAX_SIZE 100
#define MAX_SIZE_MATRIX 25
#define MAX_ROWS 5
#define MAX_COLUMNS 5
#define MAX_ROWS_D 3
#define MAX_COLUMNS_D 3
#define MIN 0

int menu(){
	int opcion;
	do{
		printf("\n\nBienvenido a la calculadora introduzca la operación que desea realizar:"
				"\n ------------OPERACIONES BÁSICAS(MÁXIMO 100 NÚMEROS)------------"
		   		"\n 1.Introduzca 1 para realizar una suma."
				"\n 2.Introduzca 2 para realizar una resta."
				"\n 3.Introduzca 3 para realizar una multiplicación."
				"\n 4.Introduzca 4 para realizar una división."
				"\n\n ------------OPERACIONES CON VECTORES(TAMAÑO MÁXIMO 100)------------"
				"\n 5.Introduzca 5 para sumar componentes de 2 vectores"
				"\n 6.Introduzca 6 para restar componentes de 2 vectores"
				"\n 7.Introduzca 7 para multiplicar componentes de 2 vectores"
				"\n 8.Introduzca 8 para dividir componentes de 2 vectores"
				"\n\n ------------OPERACIONES CON MATRICES CUADRADAS(MÁXIMO 5X5)------------"
				"\n 9.Introduzca 9 para sumar 2 matrices cuadradas"
				"\n 10.Introduzca 10 para restar 2 matrices cuadrada"
				"\n 11.Introduzca 11 para multiplicar 2 matrices(NO TIENE PORQUE SER CUADRADAS)"
				"\n 12.Introduzca 12 para calcular determinante de una matriz(MÁXIMO MATRICES DE 3x3)"
				"\n 13.Introduzca 13 para salir\n");
		scanf("%d",&opcion);
	}while(opcion>13 || opcion<1);
	
	return opcion;
}

void imprimirVectorResultado(double resultado[],int tamanio){
	printf("\nImprimimos Vector resultado:\n [");
	for(int i=0;i<tamanio;i++){
		printf("%lf ",resultado[i]);
	}
	printf("]\n");
}

void imprimirMatrizResultado(double resultado[], int filas, int columnas){
	printf("\nImprimimos Matriz resultado:\n");
	for(int i=0;i<filas;i++){
		for(int j=0;j<columnas;j++){
			printf("[%lf] ",resultado[i*columnas+j]);
		}
		printf("\n");
	}
}


void
calprog_1(char *host, double_vector vector1, double_vector vector2, double_matrix matrix1, double_matrix matrix2, int opcion)
{
	CLIENT *clnt;
	calc_res  *result;
	calc_res  *determinant;
	calc_vec  *result_v;
	calc_mat  *result_m;
	double_vector arg1;
	double_vector vector_arg1;
	double_vector vector_arg2;
	double_matrix matrix_1_arg1;
	double_matrix matrix_1_arg2;

	matrix_1_arg1=matrix_1_arg2;

	if(opcion<5){
		arg1 = vector1;
	}else if(opcion<9){
		vector_arg1 = vector1;
		vector_arg2 = vector2;
	}else{
		matrix_1_arg1 = matrix1;
		matrix_1_arg2 = matrix2;
	}


#ifndef	DEBUG
	clnt = clnt_create (host, CALPROG, CAL_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	switch (opcion){
	case 1:
		result = add_1(arg1, clnt);
		if (result == (calc_res *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		printf("\nEl resultado es %lf \n",result->calc_res_u.result);
		break;
	case 2:
		result = substract_1(arg1, clnt);
		if (result == (calc_res *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		printf("\nEl resultado es %lf \n",result->calc_res_u.result);
		break;
	case 3:
		result = multiply_1(arg1, clnt);
		if (result == (calc_res *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		printf("\nEl resultado es %lf \n",result->calc_res_u.result);
		break;
	case 4:
		result = divide_1(arg1, clnt);
		if (result == (calc_res *) NULL) {
			clnt_perror (clnt, "call failed");
		}else if(result->errnum==-1){
			printf("\nNo se puede dividir por 0\n");
		}else{
			printf("\nEl resultado es %lf \n",result->calc_res_u.result);
		}
		break;
	case 5:
		result_v = add_vector_1(vector_arg1, vector_arg2, clnt);
		if (result_v == (calc_vec *) NULL) {
			clnt_perror (clnt, "call failed");
		}else if(result_v->errnum==-1){
			printf("\nSe produjo un error al realizar la operación\n");
		}else{
			imprimirVectorResultado(result_v->calc_vec_u.result.values,result_v->calc_vec_u.result.size);
		}
		break;
	case 6:
		result_v = substract_vector_1(vector_arg1, vector_arg2, clnt);
		if (result_v == (calc_vec *) NULL) {
			clnt_perror (clnt, "call failed");
		}else if(result_v->errnum==-1){
			printf("\nSe produjo un error al realizar la operación\n");
		}else{
			imprimirVectorResultado(result_v->calc_vec_u.result.values,result_v->calc_vec_u.result.size);
		}
		break;
	case 7:
		result_v = multiply_vector_1(vector_arg1, vector_arg2, clnt);
		if (result_v == (calc_vec *) NULL) {
			clnt_perror (clnt, "call failed");
		}else if(result_v->errnum==-1){
			printf("\nSe produjo un error al realizar la operación\n");
		}else{
			imprimirVectorResultado(result_v->calc_vec_u.result.values,result_v->calc_vec_u.result.size);
		}		
		break;
	case 8:
		result_v = divide_vector_1(vector_arg1, vector_arg2, clnt);
		if (result_v == (calc_vec *) NULL) {
			clnt_perror (clnt, "call failed");
		}else if(result_v->errnum==-1){
			printf("\nIntento dividir por 0 o se produjo u error al realizar la operación\n");
		}else{
			imprimirVectorResultado(result_v->calc_vec_u.result.values,result_v->calc_vec_u.result.size);
		}
		break;
	case 9:
		result_m = add_matrix_1(matrix_1_arg1, matrix_1_arg2, clnt);
		if (result_m == (calc_mat *) NULL) {
			clnt_perror (clnt, "call failed");
		}else if(result_m->errnum==-1){
			printf("\nSe produjo un error al realizar la operación\n");
		}else{
			imprimirMatrizResultado(result_m->calc_mat_u.result.values,result_m->calc_mat_u.result.filas,result_m->calc_mat_u.result.columnas);
		}
		break;
	case 10:
		result_m = substract_matrix_1(matrix_1_arg1, matrix_1_arg2, clnt);
		if (result_m == (calc_mat *) NULL) {
			clnt_perror (clnt, "call failed");
		}else if(result_m->errnum==-1){
			printf("\nSe produjo un error al realizar la operación\n");
		}else{
			imprimirMatrizResultado(result_m->calc_mat_u.result.values,result_m->calc_mat_u.result.filas,result_m->calc_mat_u.result.columnas);
		}
		break;
	case 11:
		result_m = multiply_matrix_1(matrix_1_arg1, matrix_1_arg2, clnt);
		if (result_m == (calc_mat *) NULL) {
			clnt_perror (clnt, "call failed");
		}else if(result_m->errnum==-1){
			printf("\nSe produjo un error al realizar la operación\n");
		}else{
			imprimirMatrizResultado(result_m->calc_mat_u.result.values,result_m->calc_mat_u.result.filas,result_m->calc_mat_u.result.columnas);
		}
		break;
	case 12:
		determinant = determinant_matrix_1(matrix_1_arg1, clnt);
		if (determinant == (calc_res *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		if(determinant->errnum==-1){
			printf("\nError introdujo una matriz mayor a 3X3 o no era una matriz cuadrada");
		}else{
			printf("\nEl determinante de la Matriz es %lf \n",determinant->calc_res_u.result);
		}
		break;
	case 13:
		exit(0);
		break;
	default:
		break;
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
char *host;
	int opcion=0,cant=0,tipo=0,filas=0,columnas=0,continuar=1;
	double valor=0.0;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	host = argv[1];
	double_vector vector1,vector2;
	double_matrix matriz1, matriz2;
	do{
		opcion = menu();
		if(opcion!=13){
			if(opcion<5)tipo=1;
			else if(opcion<9) tipo=2;
			else if(opcion<11) tipo=3;
			else if(opcion==11) tipo=4;
			else tipo=5;

			switch (tipo)
			{
			case 1:
				do{
					printf("Cuantos número quiere añadir a la operación: ");
					scanf("%d",&cant);
				}while(cant>MAX_SIZE || cant<MIN);
				for(int i=0;i<cant;i++){
					printf("Introduzca el siguiente número: ");
					scanf("%lf",&valor);
					vector1.values[i]=valor;
				}
				vector1.size=cant;
				calprog_1 (host,vector1,vector2,matriz1,matriz2,opcion);
				break;
			case 2:
				do{
					printf("De que tamaño quiere que sean los vectores(ambos tendrán mismo tamaño): ");
					scanf("%d",&cant);
				}while(cant>MAX_SIZE || cant<MIN);

				for(int i=0;i<cant;i++){
					printf("\nVector1[%d]: ",i+1);
					scanf("%lf",&valor);
					vector1.values[i]=valor;
					printf("\nVector2[%d]: ",i+1);
					scanf("%lf",&valor);
					vector2.values[i]=valor;
				}
				vector1.size=cant;
				vector2.size=cant;
				calprog_1 (host,vector1,vector2,matriz1,matriz2,opcion);
				break;
			case 3:
				do{
					printf("Cuantas filas quiere que tengan las matrices(ambas tendrán las mismas): ");
					scanf("%d",&filas);
					printf("Cuantas columnas quiere que tengan las matrices(ambas tendrán las mismas): ");
					scanf("%d",&columnas);
				}while((filas>MAX_ROWS || filas<MIN) && (columnas>MAX_COLUMNS || columnas<MIN));

				for(int i=0;i<filas;i++){
					for(int j=0;j<columnas;j++){
						printf("\nMatriz1[%d][%d]: ",i,j);
						scanf("%lf",&valor);
						matriz1.values[i*columnas+j]=valor;
						printf("\nMatriz2[%d][%d]: ",i,j);
						scanf("%lf",&valor);
						matriz2.values[i*columnas+j]=valor;
					}
				}
				matriz1.filas=filas;
				matriz2.filas=filas;
				matriz1.columnas=columnas;
				matriz2.columnas=columnas;
				calprog_1 (host,vector1,vector2,matriz1,matriz2,opcion);
				break;
			case 4:
				do{
					printf("Cuantas filas quiere que tengan la matriz 1: ");
					scanf("%d",&filas);
					printf("Cuantas columnas quiere que tengan la matriz 1: ");
					scanf("%d",&columnas);
				}while((filas>MAX_ROWS || filas<MIN) && (columnas>MAX_COLUMNS || columnas<MIN));
				matriz1.filas=filas;
				matriz1.columnas=columnas;
				do{
					printf("Cuantas filas quiere que tengan la matriz 2: ");
					scanf("%d",&filas);
					printf("Cuantas columnas quiere que tengan la matriz 2: ");
					scanf("%d",&columnas);
				}while((filas>MAX_ROWS || filas<MIN) && (columnas>MAX_COLUMNS || columnas<MIN));
				matriz2.filas=filas;
				matriz2.columnas=columnas;
				
				printf("\nRellenamos matriz 1: ");
				for(int i=0;i<matriz1.filas;i++){
					for(int j=0;j<matriz1.columnas;j++){
						printf("\nMatriz1[%d][%d]: ",i,j);
						scanf("%lf",&valor);
						matriz1.values[i*matriz1.columnas+j]=valor;
					}
				}

				printf("\nRellenamos matriz 2: ");
				for(int i=0;i<matriz2.filas;i++){
					for(int j=0;j<matriz2.columnas;j++){
						printf("\nMatriz2[%d][%d]: ",i,j);
						scanf("%lf",&valor);
						matriz2.values[i*matriz2.columnas+j]=valor;
					}
				}
				calprog_1 (host,vector1,vector2,matriz1,matriz2,opcion);
				break;
			case 5:
				do{
					printf("Cuantas filas quiere que tenga la matriz: ");
					scanf("%d",&filas);
					printf("Cuantas columnas quiere que tenga la matriz: ");
					scanf("%d",&columnas);
				}while((filas>MAX_ROWS_D || filas<MIN) && (columnas>MAX_COLUMNS_D || columnas<MIN));
				
				for(int i=0;i<filas;i++){
					for(int j=0;j<columnas;j++){
						printf("\nMatriz[%d][%d]: ",i,j);
						scanf("%lf",&valor);
						matriz1.values[i*columnas+j]=valor;
					}
				}

				printf("\nMatriz Introducida: \n");
				for(int i=0;i<filas;i++){
					for(int j=0;j<columnas;j++){
						printf("[%lf] ",matriz1.values[i*columnas+j]);
					}
					printf("\n");
				}
				matriz1.filas=filas;
				matriz2.columnas=columnas;
				calprog_1 (host,vector1,vector2,matriz1,matriz2,opcion);
				break;
			default:
				break;
			}
			printf("\nDesea realizar otra operación: "
				   "\n1. Introduzca cualquier número en caso de que si: "
				   "\n2. Introduzca 0 en caso de que no: \n");
			scanf("%d",&continuar);
			if(continuar==0) opcion=13;
		}
	}while(opcion!=13);
exit (0);
}
