/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dir.h"

readdir_res *
readdir_1_svc(nametype arg1,  struct svc_req *rqstp)
{
	static readdir_res  result;

	/*
	 * insert server code here
	 */

	return &result;
}
