#
# Autogenerated by Thrift Compiler (0.16.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys

from thrift.transport import TTransport
all_structs = []


class Matrix(object):
    """
    Attributes:
     - matriz
     - filas
     - columnas

    """


    def __init__(self, matriz=None, filas=None, columnas=None,):
        self.matriz = matriz
        self.filas = filas
        self.columnas = columnas

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.LIST:
                    self.matriz = []
                    (_etype3, _size0) = iprot.readListBegin()
                    for _i4 in range(_size0):
                        _elem5 = []
                        (_etype9, _size6) = iprot.readListBegin()
                        for _i10 in range(_size6):
                            _elem11 = iprot.readDouble()
                            _elem5.append(_elem11)
                        iprot.readListEnd()
                        self.matriz.append(_elem5)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.filas = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.I32:
                    self.columnas = iprot.readI32()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('Matrix')
        if self.matriz is not None:
            oprot.writeFieldBegin('matriz', TType.LIST, 1)
            oprot.writeListBegin(TType.LIST, len(self.matriz))
            for iter12 in self.matriz:
                oprot.writeListBegin(TType.DOUBLE, len(iter12))
                for iter13 in iter12:
                    oprot.writeDouble(iter13)
                oprot.writeListEnd()
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.filas is not None:
            oprot.writeFieldBegin('filas', TType.I32, 2)
            oprot.writeI32(self.filas)
            oprot.writeFieldEnd()
        if self.columnas is not None:
            oprot.writeFieldBegin('columnas', TType.I32, 3)
            oprot.writeI32(self.columnas)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(Matrix)
Matrix.thrift_spec = (
    None,  # 0
    (1, TType.LIST, 'matriz', (TType.LIST, (TType.DOUBLE, None, False), False), None, ),  # 1
    (2, TType.I32, 'filas', None, None, ),  # 2
    (3, TType.I32, 'columnas', None, None, ),  # 3
)
fix_spec(all_structs)
del all_structs
