/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"
#include <errno.h>

calc_res *
add_1_svc(double arg1, double arg2,  struct svc_req *rqstp)
{
	static calc_res  result;

	xdr_free(xdr_calc_res, &result);

	result.calc_res_u.result = arg1 + arg2;

	result.errnum=0;
	return &result;
}

calc_res *
substract_1_svc(double arg1, double arg2,  struct svc_req *rqstp)
{
	static calc_res  result;

	xdr_free(xdr_calc_res, &result);

	result.calc_res_u.result = arg1 - arg2;

	result.errnum=0;
	return &result;
}

calc_res *
multiply_1_svc(double arg1, double arg2,  struct svc_req *rqstp)
{
	static calc_res  result;

	xdr_free(xdr_calc_res, &result);

	result.calc_res_u.result = arg1 * arg2;

	result.errnum=0;
	return &result;
}

calc_res *
divide_1_svc(double arg1, double arg2,  struct svc_req *rqstp)
{
	static calc_res  result;

	xdr_free(xdr_calc_res, &result);

	if(arg2==0.0){
		result.errnum=errno;
		return (&result);
	}else{
		result.errnum=0;
		result.calc_res_u.result = arg1 / arg2;
	}


	return &result;
}
