/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"
#include <errno.h>
#include <stdio.h>
#include <stdbool.h>
#include <math.h>

int menu(){
	int opcion;
	printf("Bienvenido a la calculadora porfavor introduzca que operación desea realizar:"
		   "\n 1.Introduzca 1 para realizar una suma."
			"\n 2.Introduzca 2 para realizar una resta."
			"\n 3.Introduzca 3 para realizar una multiplicación."
			"\n 4.Introduzca 4 para realizar una división.\n\n");
	scanf("%d",&opcion);
	return opcion;
}

void
calprog_1(char *host, double arg1, double arg2,int opcion)
{
	CLIENT *clnt;
	calc_res  *result;
	bool valor=true;

#ifndef	DEBUG
	clnt = clnt_create (host, CALPROG, CAL_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	do{
		switch (opcion){
		case 1:
			printf("Valores %f y %f ", arg1,arg2);
			result = add_1(arg1, arg2, clnt);
			if (result == (calc_res *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			printf("El resultado es %lf \n",result->calc_res_u.result);
			break;
		case 2:
			result = substract_1(arg1, arg2, clnt);
			if (result == (calc_res *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			printf("El resultado es %lf \n",result->calc_res_u.result);
			break;
		case 3:
			result = multiply_1(arg1, arg2, clnt);
			if (result == (calc_res *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			printf("El resultado es %lf \n",result->calc_res_u.result);
			break;
		case 4:
			result = divide_1(arg1, arg2, clnt);
			printf("Errnum vale %lf ", result->errnum);
			if (result == (calc_res *) NULL) {
				clnt_perror (clnt, "call failed");
			}else if(result->errnum==errno){
				printf("No se puede divdir por 0");
			}else{
				printf("El resultado es %lf \n",result->calc_res_u.result);
				break;
			}
		default:
			printf("La opción que elegiste no existe, porfavor pasa un valor entre 1 y 4");
			opcion = menu();
			valor=false;
			break;
		}
	}while(!valor);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	double num1=0, num2=0;
	int opcion;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	host = argv[1];
	opcion = menu();
	printf("Introduzca el primer valor: ");
	scanf("%lf",&num1);
	printf("Introduzca el segundo valor: ");
	scanf("%lf",&num2);

	calprog_1 (host,num1,num2,opcion);
exit (0);
}
